In [10]:
import numpy as np

class CustomPerceptron(object):
  def __init__(self, n_iterations=10, random_state=1, learning_rate=0.01):
    self.n_iterations = n_iterations
    self.random_state = random_state
    self.learning_rate = learning_rate

  
  
  def fit(self, X, y):
    rgen = np.random.RandomState(self.random_state)
    self.coef_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
    for _ in range(self.n_iterations):
      for xi, expected_value in zip(X, y):
        predicted_value = self.predict(xi)
        self.coef_[1:] = self.coef_[1:] + self.learning_rate * (expected_value - predicted_value) * xi
        self.coef_[0] = self.coef_[0] + self.learning_rate * (expected_value - predicted_value) * 1


  def net_input(self, X):
    weighted_sum = np.dot(X, self.coef_[1:]) + self.coef_[0]
    return weighted_sum


  def activation_function(self, X):
    weighted_sum = self.net_input(X)
    return np.where(weighted_sum >= 0.0, 1, -1)


  def predict(self, X):
    return self.activation_function(X) 


  def score(self, X, y):
    misclassified_data_count = 0
    for xi, target in zip(X, y):
      output = self.predict(xi)
      if(target != output):
        misclassified_data_count += 1
    total_data_count = len(X)
    self.score_ = (total_data_count - misclassified_data_count)/total_data_count
    return self.score_

In [5]:
perceptron = CustomPerceptron()

perceptron.fit(x, d)

perceptron.score(x, d)

0.0

In [8]:
print(perceptron.coef_)

[ 1.27624345  0.29082544  5.60992128 -3.12294869]


In [1]:
from google.colab import files
uploaded = files.upload()

Saving Appendix_A (1).xlsx to Appendix_A (1).xlsx


In [2]:
import pandas as pd
import io
import numpy as np
df2 = pd.read_excel('Appendix_A (1).xlsx')
x = pd.DataFrame(df2, columns=('x1', 'x2', 'x3'))
x = np.array(x)
d = pd.DataFrame(df2['d'])
d = np.array(d)
 
print(x)
print(d)

[[-0.6508  0.1097  4.0009]
 [-1.4492  0.8896  4.4005]
 [ 2.085   0.6876 12.071 ]
 [ 0.2626  1.1476  7.7985]
 [ 0.6418  1.0234  7.0427]
 [ 0.2569  0.673   8.3265]
 [ 1.1155  0.6043  7.4446]
 [ 0.0914  0.3399  7.0677]
 [ 0.0121  0.5256  4.6316]
 [-0.0429  0.466   5.4323]
 [ 0.434   0.687   8.2287]
 [ 0.2735  1.0287  7.1934]
 [ 0.4839  0.4851  7.485 ]
 [ 0.4089 -0.1267  5.5019]
 [ 1.4391  0.1614  8.5843]
 [-0.9115 -0.1973  2.1962]
 [ 0.3654  1.0475  7.4858]
 [ 0.2144  0.7515  7.1699]
 [ 0.2013  1.0014  6.5489]
 [ 0.6483  0.2183  5.8991]
 [-0.1147  0.2242  7.2435]
 [-0.797   0.8795  3.8762]
 [-1.0625  0.6366  2.4707]
 [ 0.5307  0.1285  5.6883]
 [-1.22    0.7777  1.7252]
 [ 0.3957  0.1076  5.6623]
 [-0.1013  0.5989  7.1812]
 [ 2.4482  0.9455 11.2095]
 [ 2.0149  0.6192 10.9263]
 [ 0.2012  0.2611  5.4631]]
[[-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [ 1]]
